//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContextDB : DbContext
    {
        public ContextDB()
            : base("name=ContextDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employee> Employees { get; set; }
        public DbSet<OverseeingPerson> OverseeingPersons { get; set; }
        public DbSet<ResourcesNeeded> ResourcesNeededs { get; set; }
        public DbSet<Responsible> Responsibles { get; set; }
        public DbSet<RoleAccreditation> RoleAccreditations { get; set; }
        public DbSet<RoleNQFRegistration> RoleNQFRegistrations { get; set; }
        public DbSet<RoleQualityAudit> RoleQualityAudits { get; set; }
    }
}
