//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.OverseeingPersons = new HashSet<OverseeingPerson>();
            this.ResourcesNeededs = new HashSet<ResourcesNeeded>();
            this.Responsibles = new HashSet<Responsible>();
        }
    
        public int MemberID { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string PossitionAdd { get; set; }
        public string Department { get; set; }
        public string Password { get; set; }
        public int Action { get; set; }
    
        public virtual ICollection<OverseeingPerson> OverseeingPersons { get; set; }
        public virtual ICollection<ResourcesNeeded> ResourcesNeededs { get; set; }
        public virtual ICollection<Responsible> Responsibles { get; set; }
        public virtual RoleAccreditation RoleAccreditation { get; set; }
        public virtual RoleNQFRegistration RoleNQFRegistration { get; set; }
        public virtual RoleQualityAudit RoleQualityAudit { get; set; }
    }
}
