//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourcesNeeded
    {
        public int ID { get; set; }
        public int MemberID { get; set; }
        public string QualificationName { get; set; }
        public Nullable<int> NQFLevel { get; set; }
        public string NQFIDNumber { get; set; }
        public string NQFRegistrationStatus { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string Emails { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
